version: '3.9'

services:
  model:
    build:
      context: ./hlky/
      args:
        # You can choose any commit sha from https://github.com/hlky/stable-diffusion/commits/main
        # USE AT YOUR OWN RISK! otherwise just leave it empty.
        WEBUI_SHA:
    ports:
      - "7860:7860"
    volumes:
      - ./cache:/cache
      - ./output:/output
      - ./models:/models
    environment:
      - CLI_ARGS=--no-progressbar-hiding
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
